requires 'Mojolicious';
requires 'DBI';
requires 'DBD::Pg';
requires 'Crypt::Bcrypt';
requires 'JSON::XS';
requires 'Text::CSV';
requires 'Try::Tiny';

on 'test' => sub {
    requires 'Test::More';
    requires 'Test::Mojo';
};