#!/usr/bin/env perl
use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;

# Use PORT env var if available (Railway), otherwise default to 3000
my $port = $ENV{PORT} || 3000;
@ARGV = ('daemon', '-l', "http://*:$port") unless @ARGV;

use Mojolicious::Commands;
Mojolicious::Commands->start_app('LabTrack');