#!/usr/bin/env perl
use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;

my $port = $ENV{PORT} || 3000;
# Force numeric
$port = int($port);
print "Starting LabTrack on port $port (PORT env: " . ($ENV{PORT} // 'not set') . ")\n";

use Mojolicious::Commands;
Mojolicious::Commands->start_app('LabTrack', 'daemon', '-l', "http://0.0.0.0:$port");